version: "3.8"

services:
  db:
    image: supabase/postgres:latest
    build:
      args:
        VERSION: ${POSTGRES_VERSION:-14.1}
    restart: "no"
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 2s
      timeout: 2s
      retries: 10
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: password

  pg_prove:
    image: horrendo/pg_prove
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
    volumes:
      - ./migrations/tests:/tests
    command: pg_prove /tests/test.sql
