pg_database:
  query: "SELECT SUM(pg_database_size(pg_database.datname)) / (1024 * 1024) as size_mb FROM pg_database"
  master: true
  cache_seconds: 30
  metrics:
    - size_mb:
        usage: "GAUGE"
        description: "Disk space used by the database"

auth_users:
  query: "select count(id) as user_count from auth.users"
  master: true
  cache_seconds: 30
  metrics:
    - user_count:
        usage: "GAUGE"
        description: "Number of users in the project db"

storage:
  query: "select sum(size) / (1024 * 1024) as storage_size_mb from storage.get_size_by_bucket()"
  master: true
  cache_seconds: 30
  metrics:
    - storage_size_mb:
        usage: "GAUGE"
        description: "The total size used for all storage buckets, in mb"

pg_stat_database:
  query: "SELECT sum(numbackends) as num_backends FROM pg_stat_database"
  master: true
  metrics:
    - num_backends:
        usage: "GAUGE"
        description: "The number of active backends"

pg_stat_statements:
  query: "SELECT sum(calls) as total_queries, sum(total_time / 1000) as total_time_seconds FROM pg_stat_statements t1 JOIN pg_database t3 ON (t1.dbid=t3.oid)"
  master: true
  metrics:
    - total_queries:
        usage: "COUNTER"
        description: "Number of times executed"
    - total_time_seconds:
        usage: "COUNTER"
        description: "Total time spent, in seconds"
