[global]
archive-async = n
archive-copy = y
backup-standby = prefer
compress-type = zst
delta = y
expire-auto = y
link-all = y
log-level-console = info
log-level-file = detail
log-subprocess = y
resume = n
start-fast = y
