- name: tuned - install and configure
  when:
    - (stage2_nix or nixpkg_mode or debpkg_mode)
  block:
    - name: tuned - install package
      ansible.builtin.apt:
        force_apt_get: true
        name: 'tuned'
        policy_rc_d: 101
        state: 'present'
        update_cache: true
      become: true

    - name: tuned - create profile directory
      ansible.builtin.file:
        group: 'root'
        mode: '0755'
        owner: 'root'
        path: '/etc/tuned/profiles/postgresql'
        state: 'directory'
      become: true

    - name: tuned - create profile symlink
      ansible.builtin.file:
        force: true
        group: 'root'
        mode: '0755'
        owner: 'root'
        path: '/etc/tuned/postgresql'
        src: '/etc/tuned/profiles/postgresql'
        state: 'link'
      become: true

    - name: tuned - configure profile
      become: true
      community.general.ini_file:
        create: true
        group: 'root'
        mode: '0644'
        no_extra_spaces: true
        option: "{{ item.option }}"
        path: '/etc/tuned/profiles/postgresql/tuned.conf'
        section: "{{ item.section }}"
        state: 'present'
        value: "{{ item.value }}"
      loop:
        - { section: 'cpu',    option: 'governor',                       value: 'performance' }
        - { section: 'main',   option: 'summary',                        value: 'Tuned profile for PostgreSQL' }
        - { section: 'sysctl', option: 'net.core.somaxconn',             value: 16834 }
        - { section: 'sysctl', option: 'net.ipv4.ip_local_port_range',    value: '1025 65000' }
        - { section: 'sysctl', option: 'net.ipv4.ip_local_reserved_ports', value: '3000,3001,8085,9122,9187,9999' }
        - { section: 'sysctl', option: 'net.ipv4.tcp_keepalive_intvl',   value: 60 }
        - { section: 'sysctl', option: 'net.ipv4.tcp_keepalive_time',    value: 1800 }
        - { section: 'sysctl', option: 'vm.panic_on_oom',                value: 1 }
        - { section: 'vm',     option: 'transparent_hugepages',           value: 'never' }

    - name: tuned - configure Intel CPUs for maximum performance
      become: true
      community.general.ini_file:
        create: true
        group: 'root'
        mode: '0644'
        no_extra_spaces: true
        option: "{{ item.option }}"
        path: '/etc/tuned/profiles/postgresql/tuned.conf'
        section: "{{ item.section }}"
        state: 'present'
        value: "{{ item.value }}"
      loop:
        - { section: 'cpu', option: 'energy_perf_bias', value: 'performance' }
        - { section: 'cpu', option: 'min_perf_pct',     value: '100' }
      when:
        - ansible_facts['processor'][0] is search("GenuineIntel", ignorecase=True)

    - name: tuned - set kernel.panic
      become: true
      community.general.ini_file:
        create: true
        group: 'root'
        mode: '0644'
        no_extra_spaces: true
        option: 'kernel.panic'
        path: '/etc/tuned/profiles/postgresql/tuned.conf'
        section: 'sysctl'
        state: 'present'
        value: 10
      when:
        - (debpkg_mode or nixpkg_mode)

    - name: tuned - enable zswap if swap is present
      when:
        - ansible_facts['swaptotal_mb'] > 0
      block:
        - name: tuned - decrease kernel swappiness
          become: true
          community.general.ini_file:
            create: true
            group: 'root'
            mode: '0644'
            no_extra_spaces: true
            option: 'vm.swappiness'
            path: '/etc/tuned/profiles/postgresql/tuned.conf'
            section: 'sysctl'
            state: 'present'
            value: 10

        - name: tuned - load zstd compressor module
          become: true
          community.general.modprobe:
            name: 'zstd'
            persistent: 'present'
            state: 'present'

        - name: tuned - configure and enable zswap
          ansible.builtin.shell:
            cmd: "echo {{ item.value }}  > /sys/module/zswap/parameters/{{ item.param }}"
          loop:
            - { param: 'compressor',       value: 'zstd' }
            - { param: 'max_pool_percent', value: '10' }
            - { param: 'zpool',            value: 'zsmalloc' }
            - { param: 'enabled',          value: 'Y' }

    - name: tuned - activate service
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        name: 'tuned'
        state: "{{ 'restarted' if stage2_nix else 'stopped' }}"
      become: true

    - name: tuned - activate postgresql profile
      ansible.builtin.command:
        cmd: tuned-adm profile postgresql
      become: true
      changed_when: false
      when: stage2_nix
