- name: Kong - system user
  user: name=kong

# Kong installation steps from https://developer.konghq.com/gateway/install/
- name: Kong - package manager installation
  shell: |
    curl -1sLf "https://packages.konghq.com/public/gateway-311/gpg.CF9CDA9D288571F9.key" |  gpg --dearmor | sudo tee /usr/share/keyrings/kong-gateway-311-archive-keyring.gpg > /dev/null
    curl -1sLf "https://packages.konghq.com/public/gateway-311/config.deb.txt?distro=ubuntu&codename=noble" | sudo tee /etc/apt/sources.list.d/kong-gateway-311.list > /dev/null
    sudo apt-get update && sudo apt-get install -y kong-enterprise-edition={{ kong_version }}

- name: Kong - configuration
  template:
    src: files/kong_config/kong.conf.j2
    dest: /etc/kong/kong.conf

- name: Kong - hand over ownership of /usr/local/kong to user kong
  file:
    path: /usr/local/kong
    recurse: yes
    owner: kong

# [warn] ulimit is currently set to "1024". For better performance set it to at least
# "4096" using "ulimit -n"
- name: Kong - bump up ulimit
  pam_limits:
    limit_item: nofile
    limit_type: soft
    domain: kong
    value: "4096"

- name: Kong - create env file
  template:
    src: files/kong_config/kong.env.j2
    dest: /etc/kong/kong.env

- name: Kong - create service file
  template:
    src: files/kong_config/kong.service.j2
    dest: /etc/systemd/system/kong.service

- name: Kong - disable service
  systemd:
    enabled: no
    name: kong
    state: stopped
    daemon_reload: yes
