- name: Create pgBackRest group
  ansible.builtin.group:
    name: pgbackrest
    state: present
  when: nixpkg_mode

- name: Create pgBackRest user
  ansible.builtin.user:
    comment: pgBackRest user
    group: pgbackrest
    groups: pgbackrest, postgres
    home: /var/lib/pgbackrest
    name: pgbackrest
    shell: /sbin/nologin
    system: true
  when: nixpkg_mode

- name: Install pgBackRest
  become: true
  become_user: pgbackrest
  ansible.builtin.shell: |
    sudo -u pgbackrest bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install github:supabase/postgres/{{ git_commit_sha }}#pg-backrest"
  changed_when: true
  when: stage2_nix

- name: Create needed directories for pgBackRest
  ansible.legacy.file:
    group: postgres
    mode: '0770'
    owner: pgbackrest
    path: "{{ backrest_dir }}"
    state: directory
  loop:
    - /etc/pgbackrest/conf.d
    - /var/lib/pgbackrest
    - /var/spool/pgbackrest
    - /var/log/pgbackrest
  loop_control:
    loop_var: backrest_dir
  when: nixpkg_mode

- name: Symlink pgbackrest.conf
  ansible.legacy.file:
    force: true
    path: /etc/pgbackrest/pgbackrest.conf
    src: /etc/pgbackrest.conf
    state: link

- name: Move pgBackRest files to /etc/pgbackrest
  ansible.legacy.copy:
    group: postgres
    dest: "/etc/pgbackrest/{{ conf_item['path'] }}/{{ conf_item['name'] }}"
    mode: '0644'
    owner: pgbackrest
    src: "files/pgbackrest_config/{{ conf_item['name'] }}"
  loop:
    - {name: computed_globals.conf, path: conf.d}
    - {name: pgbackrest.conf, path: ''}
    - {name: repo1_async.conf, path: conf.d}
    - {name: repo1_encrypted.conf, path: conf.d}
    - {name: repo1.conf, path: conf.d}
  loop_control:
    loop_var: conf_item
  when: stage2_nix

- name: Symlink pgBackRest binary
  ansible.legacy.file:
    path: /usr/bin/pgbackrest
    src: /var/lib/pgbackrest/.nix-profile/bin/pgbackrest
    state: link

- name: Sticky bit the pgBackRest binary
  ansible.legacy.file:
    mode: '4755'
    path: /var/lib/pgbackrest/.nix-profile/bin/pgbackrest
  become: true
