name: Build AMI
description: Build both stage 1 and stage 2 AMIs

inputs:
  ami_name_prefix:
    description: 'Prefix for the AMI name'
    required: true
  arch:
    description: Architecture to build AMI for (amd64|arm64)
    required: true
  git_sha:
    description: 'Git SHA for this build'
    required: true
  packages_git_sha:
    description: 'Git SHA to install packages from'
    required: true
  postgres_version:
    description: 'PostgreSQL major version (e.g., 15)'
    required: true

outputs:
  stage2_ami_id:
    description: 'The AMI ID of the stage 2 build'
    value: ${{ steps.build-stage2.outputs.stage2_ami_id }}
  postgres_release_version:
    description: 'The PostgreSQL release version'
    value: ${{ steps.set-env-and-outputs.outputs.postgres_version }}
  execution_id:
    description: 'The execution ID for this build'
    value: ${{ steps.set-env-and-outputs.outputs.execution_id }}
  disk_usage_json:
    description: 'The stage 2 AMI root disk usage as json'
    value: ${{ steps.build-stage2.outputs.disk_usage_json }}

runs:
  using: "composite"
  steps:
    - name: Verify arch
      shell: bash
      run: |
        case ${{ inputs.arch }} in
        amd64 | arm64) ;;
        *) echo "Unknown arch input, expected:(amd64|arm64) got:${{ inputs.arch }}" >&2 && exit 1 ;;
        esac
    - name: Set Env and Outputs
      id: set-env-and-outputs
      shell: bash
      env:
        GIT_SHA: ${{ inputs.git_sha }}
        PACKER_EXECUTION_ID: ${{ inputs.postgres_version }}-${{ inputs.arch }}-${{ github.run_id }}
        POSTGRES_MAJOR_VERSION: ${{ inputs.postgres_version }}
      run: |
        echo "GIT_SHA=$GIT_SHA" >>$GITHUB_ENV

        echo "PACKER_EXECUTION_ID=$PACKER_EXECUTION_ID" >> $GITHUB_ENV
        echo "execution_id=$PACKER_EXECUTION_ID" >> $GITHUB_OUTPUT

        echo "POSTGRES_MAJOR_VERSION=$POSTGRES_MAJOR_VERSION" >> $GITHUB_ENV

        POSTGRES_VERSION=$(nix run nixpkgs#yq-go -- -er ".postgres_release.postgres$POSTGRES_MAJOR_VERSION" ansible/postgres_release.yml)
        echo "POSTGRES_VERSION=$POSTGRES_VERSION" >> $GITHUB_ENV
        echo "postgres_version=$POSTGRES_VERSION" >> $GITHUB_OUTPUT

    - name: Build AMI stage 1
      shell: bash
      env:
        AWS_MAX_ATTEMPTS: 10
        AWS_RETRY_MODE: adaptive
      run: |
        echo "::group::AMI Build: Stage 1"

        nix run .#build-ami -- stage1 ${{ inputs.arch }} \
          -var "ami_name=${{ inputs.ami_name_prefix }}" \
          -var 'ami_regions=${{ inputs.ami_regions }}' \
          -var "ansible_arguments=-e postgresql_major=$POSTGRES_MAJOR_VERSION" \
          -var "git-head-version=$GIT_SHA" \
          -var "packer-execution-id=$PACKER_EXECUTION_ID" \
          -var "postgres-version=$POSTGRES_VERSION" \
          ;

        echo "::endgroup::"

    - name: Build AMI stage 2
      id: build-stage2
      shell: bash
      env:
        AWS_MAX_ATTEMPTS: 10
        AWS_RETRY_MODE: adaptive
      run: |
        echo "::group::AMI Build: Stage 2"

        nix run .#build-ami -- stage2 ${{ inputs.arch }} \
          -var "ami_name=${{ inputs.ami_name_prefix }}" \
          -var "git-head-version=$GIT_SHA" \
          -var "git_sha=${{ inputs.packages_git_sha }}" \
          -var "packer-execution-id=$PACKER_EXECUTION_ID" \
          -var "postgres_major_version=$POSTGRES_MAJOR_VERSION" \
          -var "postgres-version=$POSTGRES_VERSION" \
          ;

        echo "::endgroup::"
