- name: PG logging conf
  template:
    src: files/postgresql_config/postgresql-stdout-log.conf
    dest: /etc/postgresql/logging.conf
    group: postgres

- name: import pgsodium_getkey_urandom.sh
  template:
    src: files/pgsodium_getkey_urandom.sh.j2
    dest: "{{ pg_bindir }}/pgsodium_getkey.sh"
    owner: postgres
    group: postgres
    mode: 0700

- name: allow pgsodium key generation
  become: yes
  file:
    path: '{{ item }}'
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0774'
  with_items:
    - /etc/postgresql-custom

- name: copy Supabase extension libs
  become: yes
  copy:
    src: /usr/lib/postgresql/lib/
    dest: /usr/lib/postgresql/{{ postgresql_major }}/lib/

- name: copy Supabase extension files
  become: yes
  copy:
    src: /var/lib/postgresql/extension/
    dest: /usr/share/postgresql/{{ postgresql_major }}/extension/
