package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	"github.com/supabase/ubuntu-cis-audit/scanner/internal/config"
	"github.com/supabase/ubuntu-cis-audit/scanner/internal/logger"
	"github.com/supabase/ubuntu-cis-audit/scanner/internal/scanners"
	"github.com/supabase/ubuntu-cis-audit/scanner/internal/spec"
)

var (
	version = "dev" // Set by ldflags during build

	// CLI flags
	configFile     string
	outputFormat   string // "yaml" or "json"
	includeDynamic bool
	includePorts   bool
	includeProcess bool
	strict         bool
	verbose        bool
	debug          bool
	logFormat      string
)

var rootCmd = &cobra.Command{
	Use:   "cis-generate-spec [output-file]",
	Short: "Generate CIS baseline specification",
	Long: `Generate a machine baseline specification for CIS audit compliance.

This tool scans the system and generates a YAML or JSON specification file
containing packages, files, kernel parameters, services, and optionally
listening ports and running processes.

Examples:
  # Generate default machine-baseline.yaml
  cis-generate-spec

  # Generate JSON output
  cis-generate-spec --format json baseline.json

  # Include dynamic checks with exclusions from config
  cis-generate-spec --config cis-config.yaml --include-dynamic --include-ports

  # Enable verbose logging to stderr
  cis-generate-spec --verbose --log-format json
`,
	Args:    cobra.MaximumNArgs(1),
	Version: version,
	RunE:    run,
}

func init() {
	rootCmd.Flags().StringVar(&configFile, "config", "", "Load exclusions from config file")
	rootCmd.Flags().StringVar(&outputFormat, "format", "yaml", "Output format: yaml or json")
	rootCmd.Flags().BoolVar(&includeDynamic, "include-dynamic", false, "Include dynamic kernel parameters")
	rootCmd.Flags().BoolVar(&includePorts, "include-ports", false, "Include listening ports")
	rootCmd.Flags().BoolVar(&includeProcess, "include-processes", false, "Include running processes")
	rootCmd.Flags().BoolVar(&strict, "strict", false, "Fail on any access errors (default: skip and warn)")
	rootCmd.Flags().BoolVar(&verbose, "verbose", false, "Enable structured logging to stderr")
	rootCmd.Flags().BoolVar(&debug, "debug", false, "Enable debug logging (implies --verbose)")
	rootCmd.Flags().StringVar(&logFormat, "log-format", "logfmt", "Log format: logfmt or json")
}

func run(cmd *cobra.Command, args []string) error {
	// Default output file
	outputFile := "machine-baseline.yaml"
	if len(args) > 0 {
		outputFile = args[0]
	}

	// Setup structured logging
	if debug {
		verbose = true
	}
	scanLogger := logger.Setup(verbose, debug, logFormat)

	// Load configuration with CLI options
	cliOpts := config.CLIOptions{
		IncludeDynamic:   includeDynamic,
		IncludePorts:     includePorts,
		IncludeProcesses: includeProcess,
	}
	cfg, err := config.Load(configFile, cliOpts)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Parse and validate output format
	var format spec.OutputFormat
	switch outputFormat {
	case "yaml":
		format = spec.FormatYAML
	case "json":
		format = spec.FormatJSON
	default:
		return fmt.Errorf("invalid output format: %s (must be yaml or json)", outputFormat)
	}

	// Create writer
	writer, err := spec.NewWriterWithFormat(outputFile, format)
	if err != nil {
		return fmt.Errorf("failed to create writer: %w", err)
	}
	defer writer.Close()

	// Get hostname for metadata
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
		scanLogger.Warn("Failed to get hostname", "error", err)
	}

	// Write header with metadata
	timestamp := time.Now().Format(time.RFC3339)
	header := fmt.Sprintf("Generated by cis-generate-spec %s on %s at %s", version, hostname, timestamp)
	if err := writer.WriteHeader(header); err != nil {
		return fmt.Errorf("failed to write header: %w", err)
	}

	// Create scan options
	opts := scanners.ScanOptions{
		Writer:         writer,
		Config:         cfg,
		IncludeDynamic: includeDynamic,
		Strict:         strict,
		Logger:         scanLogger,
	}

	// Run all scanners
	ctx := context.Background()
	result, err := scanners.RunAll(ctx, opts)
	if err != nil {
		return fmt.Errorf("scan failed: %w", err)
	}

	// Handle warnings
	if len(result.Warnings) > 0 {
		if strict {
			scanLogger.Error("Scan completed with warnings", "warnings", len(result.Warnings))
			for _, warning := range result.Warnings {
				scanLogger.Warn(warning)
			}
			os.Exit(2)
		}
	}

	// Print summary
	scanLogger.Info("Scan completed successfully",
		"output_file", outputFile,
		"format", outputFormat,
		"scanners_run", result.ScannersRun,
		"files_scanned", result.FilesScanned,
		"files_skipped", result.FilesSkipped,
		"users_scanned", result.UsersScanned,
		"services_scanned", result.ServicesScanned,
		"warnings", len(result.Warnings),
		"duration", result.Duration,
	)

	// Exit with appropriate code
	if len(result.Warnings) > 0 {
		os.Exit(1)
	}

	return nil
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
