# pgAudit
- name: pgAudit - download & install dependencies
  apt:
    pkg:
      - libssl-dev
      - libkrb5-dev
    update_cache: yes
    install_recommends: no

- name: pgAudit - download latest release
  get_url:
    url: "https://github.com/pgaudit/pgaudit/archive/refs/tags/{{ pgaudit_release }}.tar.gz"
    dest: /tmp/pgaudit-{{ pgaudit_release }}.tar.gz
    checksum: "{{ pgaudit_release_checksum }}"
    timeout: 60

- name: pgAudit - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgaudit-{{ pgaudit_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pgAudit - build
  make:
    chdir: /tmp/pgaudit-{{ pgaudit_release }}
    target: check
    params:
      USE_PGXS: 1
  become: yes

- name: pgAudit - install
  make:
    chdir: /tmp/pgaudit-{{ pgaudit_release }}
    target: install
    params:
      USE_PGXS: 1
  become: yes