# wal2json
- name: wal2json - download by commit sha
  git:
    repo: https://github.com/eulerto/wal2json.git
    dest: /tmp/wal2json
    version: "{{ wal2json_commit_sha }}"

- name: wal2json - install
  make:
    chdir: /tmp/wal2json
    target: install
  become: yes
