# pg_jsonschema
- name: pg_jsonschema - download & install dependencies
  apt:
    pkg:
      - make
      - gcc
      - pkg-config
      - clang
      - postgresql-server-dev-{{ postgresql_major }}
      - libssl-dev
    update_cache: yes
    install_recommends: no

- name: download rust/cargo installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y

- name: install cargo-pgx
  shell:
    cmd: "~/.cargo/bin/cargo install --version '={{ pgx_version }}' cargo-pgx && ~/.cargo/bin/cargo pgx init --pg{{ postgres_major }} pg_config"
  become: yes

- name: pg_jsonschema - download release
  git:
    repo: https://github.com/supabase/pg_jsonschema.git
    dest: /tmp/pg_jsonschema
    version: "{{ pg_jsonschema_release }}"
  become: yes

- name: pg_jsonschema - install
  shell:
    cmd: "~/.cargo/bin/cargo pgx install --release"
    chdir: /tmp/pg_jsonschema
  become: yes
