# pg_jsonschema
- name: Setting arch (x86)
  set_fact:
    arch: "amd64"
  when: platform == "amd64"

- name: Setting arch (arm)
  set_fact:
    arch: "arm64"
  when: platform == "arm64"

- name: install pg_jsonschema
  ansible.builtin.apt:
    deb: "https://github.com/supabase/pg_jsonschema/releases/download/{{ pg_jsonschema_release }}/pg_jsonschema-{{ pg_jsonschema_release }}-pg{{ postgres_major }}-{{ arch }}-linux-gnu.deb"
