# groonga and pgroonga

- name: groonga - download groonga
  get_url:
    url: "https://packages.groonga.org/source/groonga/groonga-{{ groonga_release }}.tar.gz"
    dest: /tmp/groonga-{{ groonga_release }}.tar.gz
    checksum: "{{ groonga_release_checksum }}"
    timeout: 60

- name: groonga - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/groonga-{{ groonga_release }}.tar.gz
    dest: /tmp
  become: yes

- name: groonga - configure
  shell:
    cmd: ./configure
    chdir: /tmp/groonga-{{ groonga_release }}
  become: yes

- name: groonga - build
  make:
    chdir: /tmp/groonga-{{ groonga_release }}
    jobs: "{{ parallel_jobs | default(omit) }}"
  become: yes

- name: groonga - install
  make:
    chdir: /tmp/groonga-{{ groonga_release }}
    target: install
  become: yes

- name: pgroonga - download pgroonga
  get_url:
    url: "https://packages.groonga.org/source/pgroonga/pgroonga-{{ pgroonga_release }}.tar.gz"
    dest: /tmp/pgroonga-{{ pgroonga_release }}.tar.gz
    checksum: "{{ pgroonga_release_checksum }}"
    timeout: 60

- name: pgroonga - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgroonga-{{ pgroonga_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pgroonga - build
  make:
    chdir: /tmp/pgroonga-{{ pgroonga_release }}
    jobs: "{{ parallel_jobs | default(omit) }}"
  become: yes

- name: pgroonga - install
  make:
    chdir: /tmp/pgroonga-{{ pgroonga_release }}
    target: install
  become: yes
  
- name: groonga - cleanup
  file:
    state: absent
    path: /tmp/groonga-{{ groonga_release }}
  become: yes
  
- name: pgroonga - cleanup
  file:
    state: absent
    path: /tmp/pgroonga-{{ pgroonga_release }}
  become: yes
