# hypopg
- name: hypopg - download by commit sha
  git:
    repo: https://github.com/HypoPG/hypopg.git
    dest: /tmp/hypopg
    version: "{{ hypopg_release }}"

- name: hypopg - install
  make:
    chdir: /tmp/hypopg
    target: install
  become: yes

- name: hypopg - cleanup
  file:
    state: absent
    path: /tmp/hypopg
