# pg_repack
- name: pg_repack - download & install dependencies
  apt:
    pkg:
      - liblz4-dev
      - libz-dev
      - libzstd-dev
      - libreadline-dev
    update_cache: yes
    install_recommends: no

- name: pg_repack - download latest release
  git:
    repo: https://github.com/reorg/pg_repack.git
    dest: /tmp/pg_repack
    version: "ver_{{ pg_repack_release }}"
  become: yes

- name: pg_repack - build
  make:
    chdir: /tmp/pg_repack
    params:
      USE_PGXS: 1
  become: yes

- name: pg_repack - install
  make:
    chdir: /tmp/pg_repack
    target: install
    params:
      USE_PGXS: 1
  become: yes

- name: pg_repack - cleanup
  file:
    state: absent
    path: /tmp/pg_repack
