# pg_tle
- name: pg_tle - download
  git:
    repo: https://github.com/aws/pg_tle.git
    dest: /tmp/pg_tle
    version: v1.0.1

- name: pg_tle - install
  make:
    chdir: /tmp/pg_tle
    target: install
  become: yes
