- name: Build Supabase Postgres
  hosts: localhost
  gather_facts: false

  vars_files:
    - ./vars.yml

  tasks:
    - set_fact: postgres_bin_dir: "postgresql/14/bin"

    - name: Setup container
      import_tasks: tasks/docker/setup.yml

    - name: Install Postgres extensions
      import_tasks: tasks/setup-extensions.yml

    - name: Cleanup container
      import_tasks: tasks/docker/cleanup.yml