name: Ansible Test

on:
  push:
    branches:
      - feat/ansible-testing
  pull_request:
    branches:
      - feat/ansible-testing

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.29.1/install
          extra_nix_config: |
            substituters = https://cache.nixos.org https://nix-postgres-artifacts.s3.amazonaws.com
            trusted-public-keys = nix-postgres-artifacts:dGZlQOvKcNEjvT7QEAJbcV6b6uk7VF/hWMjhYleiaLI=% cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Run Ansible Test
        run: nix run .#ansible-test
