name: Check System Manager

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  check-system-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD

      - name: Install nix
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: 'true'
        env:
          DEV_AWS_ROLE: ${{ secrets.DEV_AWS_ROLE }}
          NIX_SIGN_SECRET_KEY: ${{ secrets.NIX_SIGN_SECRET_KEY }}

      - name: Run check-system-manager
        run: nix build .#checks.x86_64-linux.check-system-manager -L
