name: Release OrioleDB on Dockerhub

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/dockerhub-release-orioledb.yml"
      - "docker/orioledb/*"
      - "common.vars*"

jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      docker_version: orioledb-${{ steps.settings.outputs.postgres-version }}
      image_tag: supabase/postgres:orioledb-${{ steps.settings.outputs.postgres-version }}
      build_args: ${{ steps.args.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - id: settings
        # Remove spaces and quotes to get the raw version string
        run: sed -r 's/(\s|\")+//g' common.vars.pkr.hcl >> $GITHUB_OUTPUT
      - id: args
        uses: mikefarah/yq@master
        with:
          cmd: yq 'to_entries | map(select(.value|type == "!!str")) |  map(.key + "=" + .value) | join("\n")' 'ansible/vars.yml'

  build_image:
    needs: settings
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: [self-hosted, X64]
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 180
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: build
        uses: docker/build-push-action@v5
        with:
          file: docker/orioledb/Dockerfile
          push: true
          build-args: |
            ${{ needs.settings.outputs.build_args }}
          target: production
          tags: ${{ needs.settings.outputs.image_tag }}_${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=${{ github.ref_name }}-orioledb-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-orioledb-${{ matrix.arch }}

  merge_manifest:
    needs: [settings, build_image]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Merge multi-arch manifests
        run: |
          docker buildx imagetools create -t ${{ needs.settings.outputs.image_tag }} \
          ${{ needs.settings.outputs.image_tag }}_amd64 \
          ${{ needs.settings.outputs.image_tag }}_arm64

  publish:
    needs: [settings, merge_manifest]
    # Call workflow explicitly because events from actions cannot trigger more actions
    uses: ./.github/workflows/mirror.yml
    with:
      version: ${{ needs.settings.outputs.docker_version }}
    secrets: inherit
