name: Nix Eval

on:
  workflow_call:
    outputs:
      matrix:
        description: 'Generated build matrix'
        value: ${{ jobs.eval.outputs.matrix }}
    secrets:
      DEV_AWS_ROLE:
        required: false
      NIX_SIGN_SECRET_KEY:
        required: false

jobs:
  eval:
    runs-on: blacksmith-32vcpu-ubuntu-2404
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install nix
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: 'true'
        env:
          DEV_AWS_ROLE: ${{ secrets.DEV_AWS_ROLE }}
          NIX_SIGN_SECRET_KEY: ${{ secrets.NIX_SIGN_SECRET_KEY }}
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu -o pipefail
          result=$(nix run --accept-flake-config .\#github-matrix -- checks legacyPackages)
          echo matrix="$result" >> "$GITHUB_OUTPUT"
