name: Test Database
on:
  workflow_dispatch:
    inputs:
      postgres_version:
        type: choice
        options:
          - "15"
          - "17"
          - orioledb-17
        required: true
  workflow_call:
    inputs:
      postgres_version:
        description: 15, 17 or orioledb-17
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  verify:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 180
    env:
      POSTGRES_PORT: 5478
      POSTGRES_PASSWORD: password
    steps:
      - name: Checkout Repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD

      - uses: ./.github/actions/nix-install-ephemeral

      - name: Resolve git sha
        id: resolve-git-sha
        uses: ./.github/actions/resolve-git-sha
        with:
          flake_input: ${{ vars.GIT_SHA_FROM_FLAKE_INPUT }}

      - name: verify schema.sql is committed
        run: |
          nix run github:supabase/postgres/${{ steps.resolve-git-sha.outputs.sha }}#dbmate-tool -- --version ${{ inputs.postgres_version }} --flake-url github:supabase/postgres/${{ steps.resolve-git-sha.outputs.sha }}
          if ! git diff --exit-code --quiet migrations/schema-${{ inputs.postgres_version }}.sql; then
            echo "Detected changes in schema.sql:"
            git diff migrations/schema-${{ inputs.postgres_version }}.sql
            exit 1
          fi
