name: Testinfra Integration Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: [self-hosted, X64]
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders

      - name: Run aio integration tests
        run: |
          pip3 install docker pytest pytest-testinfra
          pytest -vv testinfra/test_all_in_one.py
