BEGIN;
SELECT plan(4);

--- Plan for 4 tests: extension, index, exact match, and similarity search
CREATE EXTENSION IF NOT EXISTS vectorscale;

-- Test 1: Check if the vectorscale extension exists
SELECT has_extension('vectorscale', 'The vectorscale extension should exist.');

---Test 2 : Query to check if the index was created
CREATE TABLE IF NOT EXISTS document_embedding  (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   metadata JSONB,
   embedding VECTOR(4)
);

CREATE INDEX document_embedding_idx ON document_embedding
USING diskann (embedding vector_cosine_ops);

SELECT has_index('public', 'document_embedding', 'document_embedding_idx', 'The document_embedding_idx should exist.');

INSERT INTO document_embedding (metadata, embedding) VALUES 
   ('{"title": "First Document", "category": "tech"}', '[0.1, 0.2, 0.3, 0.4]'),
   ('{"title": "Second Document", "category": "science"}', '[0.5, 0.6, 0.7, 0.8]');

-- Test 3: Exact match query - should return the first document
SELECT is(
   (SELECT id FROM document_embedding WHERE embedding = '[0.1, 0.2, 0.3, 0.4]' LIMIT 1),
   1,
   'Exact match should return first document with id=1'
);

-- Test 4: Similarity search - find most similar to first document
SELECT is(
   (SELECT id FROM document_embedding ORDER BY embedding <=> '[0.1, 0.2, 0.3, 0.4]' LIMIT 1),
   1,
   'Similarity search should return most similar document (id=1)'
);

-- Cleanup
DROP INDEX IF EXISTS document_embedding_idx;
DROP TABLE IF EXISTS document_embedding;

-- Finish the test plan
SELECT * FROM finish();
ROLLBACK;